Travis: Run "brew upgrade python" to install Python 3 on macOS
As of March 2018, Travis CI fails on macOS:

Error: python 2.7.14 is already installed
To upgrade to 3.6.4_4, run `brew upgrade python`

This commit fixes the issue.